services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: jamye-db
      MYSQL_DATABASE: jamye-db
      MYSQL_USER: jamye-db
      MYSQL_PASSWORD: jamye-db
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis_test
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    volumes:
      - redis-data:/data
  spring-boot-app:
    image: jamye-backend-app
    container_name: spring-boot-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jamye-db
      SPRING_DATASOURCE_USERNAME: jamye-db
      SPRING_DATASOURCE_PASSWORD: jamye-db
      SPRING_DATA_REDIS_HOST: redis_test
      BOT_TOKEN: ${BOT_TOKEN}
      CLOUD_AWS_CREDENTIALS_ACCESSKEY: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      CLOUD_AWS_CREDENTIALS_SECRETKEY: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_SECRET_KEY: ${DISCORD_SECRET_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      FIRE_BASE: /usr/src/app/firebase-credentials.json
      FIRE_BASE_ID: your_firebase_project_id
      GOOGLE_APPLICATION_CREDENTIALS: /usr/src/app/google-credentials.json
    volumes:
      - /Users/jinhee/Workspace/jamye-backend/src/main/resources/jamye-android-firebase-adminsdk-fbsvc-fe80bc2c29.json:/usr/src/app/firebase-credentials.json
      - /Users/jinhee/Workspace/jamye-backend/src/main/resources/silken-zenith-440207-u0-58acde469bd4.json:/usr/src/app/google-credentials.json
volumes:
  mysql_data:
    driver: local
  redis-data:
    driver: local