spring:
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 20000MB
      enabled: true
  mail:
    host: smtp.gmail.com  # Gmail의 SMTP 서버 호스트
    port: 587 # Gmail SMTP 서버는 587번 포트를 사용
    username: nod15277@gmail.com
    password: kefc lfcy kgjo yugv
    properties:
      mail:
        smtp:
          auth: true # SMTP 서버에 인증 필요한 경우 true로 지정 Gmail은 요구함
          starttls:
            enable: true # SMTP 서버가 TLS를 사용하여 안전한 연결을 요구하는 경우 true로 설정
            required: true
          connectiontimeout: 5000 # 클라이언트가 SMTP 서버와의 연결을 설정하는 데 대기해야 하는 시간
          timeout: 5000 # 클라이언트가 SMTP 서버로부터 응답을 대기해야 하는 시간
          writetimeout: 5000 # 클라이언트가 작업을 완료하는데 대기해야 하는 시간
      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분 이메일 인증 코드의 만료 시간(Millisecond)
jwt:
  secretKey: fajldfklsdjfeijcnklcnsdknclnsdkncsldnckasdcnl
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
    root: info


cloud:
  aws:
    credentials:
      accessKey: AKIAXZEFIB2KCYQXHMWM
      secretKey: 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
    s3:
      bucket: jamye-image
    region:
      static: ap-northeast-2