spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secretKey: fajldfklsdjfeijcnklcnsdknclnsdkncsldnckasdcnl
logging:
  level:
    root: info