spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://jamye-service.cfek882iekrl.ap-northeast-2.rds.amazonaws.com/jamye
    username: jm
    password: jamye123!
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  shutdown: graceful