spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
cloud:
  aws:
    s3:
      bucket: jamye-image-local
discord:
  redirect: http://localhost:8081/oauth/redirect
image:
  url: http://jamye-image-local.s3-website.ap-northeast-2.amazonaws.com
kakao:
  redirect: http://localhost:8081/oauth/kakao