name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./gradlew clean build -x test

      - name: Deploy
        run: |
          cp build/libs/*.jar ~/app/jamye/
          chmod +x ~/app/jamye/deploy-systemd2.sh
          ~/app/jamye/deploy-systemd2.sh
