name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew clean build -x test
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ~/app/jamye/

      - name: Deploy
        run: |
          chmod +x ~/app/jamye/deploy-systemd2.sh
          ~/app/jamye/deploy-systemd2.sh
