name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./gradlew clean build -x test

      - name: Deploy
        run: |
          cp build/libs/*.jar ~/app/jamye/
          chmod +x ~/app/jamye/start-port.sh
          # setsid로 세션과 분리, nohup으로 로그 남김
          setsid nohup ~/app/jamye/start-port.sh > ~/app/jamye/start-port-nohup.log 2>&1 < /dev/null &
