name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
#    runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./gradlew clean build -x test

      - name: Deploy
        run: |
          cp build/libs/jamye-0.0.1-SNAPSHOT.jar ~/app/jamye/
          chmod +x ~/app/jamye/start-port.sh
          ~/app/jamye/start-port.sh